version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_USER: user            # Nombre de usuario no root
      #MYSQL_PASSWORD: password     # Contraseña para el usuario no root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql   # Aquí se monta el script SQL como un volumen
volumes:
  mysql-data: # Nombre del volumen cambiado a mysql-data